public with sharing class DemoClass {
    
    void replaceChar(String charToReplace,String charToBeReplacedWith,List<String> lstStrings){
    for(String eachString : lstStrings){
    	
    	Integer[] charsOfEachString = eachString.getChars();
		Integer[] asciiOfCharToReplace = charToReplace.getChars();
		Integer[] asciiOfCharToBeReplacedWith = charToBeReplacedWith.getChars();
    }
    	
    }
    
}